#!/bin/sh
# Xcode Cloud post-clone: regenerate the gitignored Last.fm secrets file from
# the workflow's secret environment variables (LASTFM_API_KEY / LASTFM_API_SECRET).
# Without this the cloud clone is missing LastFmSecrets.swift and fails to build.
set -e

SECRETS_PATH="$CI_PRIMARY_REPOSITORY_PATH/BoleraCore/Sources/BoleraCore/Services/LastFmSecrets.swift"

cat > "$SECRETS_PATH" <<EOF
// Generated by ci_scripts/ci_post_clone.sh from Xcode Cloud secret env vars.
// Do not commit. See LastFmSecrets.swift.example.
enum LastFmSecrets {
    static let apiKey    = "${LASTFM_API_KEY}"
    static let apiSecret = "${LASTFM_API_SECRET}"
}
EOF

echo "ci_post_clone: wrote LastFmSecrets.swift ($([ -n "$LASTFM_API_KEY" ] && echo "key set" || echo "KEY MISSING"))"
